apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcher
spec:
  template:
    spec:
      initContainers:
        - name: transfer-cache
          image: index.docker.io/sourcegraph/alpine-3.14:insiders@sha256:2624f00924c728f6d15a70c3fa5a05a9e78ffb5170089eadab961a59f466c64f
          command: ["sh", "-c", "if [[ \"$(stat -c '%u' /mnt/cache)\" -ne 100 ]]; then chown -R 100:101 /mnt/cache; fi"]
          volumeMounts:
            - mountPath: /mnt/cache
              name: cache-ssd
          securityContext:
            runAsUser: 0
